# Use this environment for reading and processing raw OCO-2 Lite files and EVI files
name: geopy
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio
  - xarray
  - rioxarray
  - dask
  - h5py
  - h5netcdf
  - ipykernel
