name: conda-env
channels:
  - defaults
  - conda-forge
  - r
dependencies:
# R tools
  - r-essentials
  - r-base
  - r-tidyverse
  - rstudio
# Core python
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - numpy
  - numba
  - pandas
  - scipy
# Data management
  - xarray
  - dask
  - netcdf4
  - h5netcdf
# Statistics / ML
  - pytorch
  - scikit-learn
  - statsmodels
  - geopy
  - gstools
# Plotting
  - matplotlib
  - seaborn
  - cartopy
  - ffmpeg
  - palettable
