name: conda-env
channels:
  - defaults
  - conda-forge
  # - r
dependencies:
  # R tools
  # - r-essentials
  # - r-base
  # - r-tidyverse
  # - rstudio
  # Core python
  - jupyter
  - jupyterlab
  # - jupyterlab-git
  - numpy
  - numba
  - pandas
  - scipy
  # Science tools
  - geopy
  - regionmask
  # Data management
  - xarray
  - dask
  - netcdf4
  - h5netcdf
  # Statistics / ML
  # - pytorch
  - scikit-learn
  - statsmodels
  # Plotting
  - matplotlib
  - seaborn
  - cartopy
  - ffmpeg
  - palettable
  - cmcrameri
