name: geostat
channels:
  - conda-forge
dependencies:
  # Core python
  - python=3.9
  - black
  - jupyterlab
  - numpy
  - numba
  - pandas
  - scipy
  - numba-scipy
  # Science tools
  - geopy
  - regionmask
  - xesmf
  # Data management
  - xarray
  - rioxarray
  - dask
  - netcdf4
  - h5netcdf
  - h5py
  - rasterio
  # Statistics / ML
  - scikit-learn
  - statsmodels
  # Plotting
  - matplotlib
  - seaborn
  - cartopy
  - cmcrameri
