name: conda-env
channels:
  - defaults
  - conda-forge
  - r
dependencies:
  - r-essentials
  - r-base
  - r-tidyverse
  - rstudio
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  - pandas
  - matplotlib
  - seaborn
  - cartopy
  - xarray
  - dask
  - netcdf4
  - ffmpeg
  - palettable
